### ISSUE TITLE
WYSIWYG on event creation is broken in some browsers

### ISSUE THREAD

**Issue by WilliamDASILVA** [Hartorn/ffs-zera#33]
The WYSIWYG editor on event creation as description field does not work as expected on Firefox & Edge.
The backspace key, and the visual buttons doesn't do anything.

Works 'ok' on Chrome.
Tested on Firefox Quantum, v57.0 (64bits), Windows 10; Microsoft Edge, v40.15063.674.0, Windows 10

**Comment by WilliamDASILVA** [comment]
Fix it or replace the package with something else. Less broken probably?

> SCRIPT5022: Got unexpected null or undefined
> react-rte.js (3232,9)

**Comment by Hartorn** [comment]
@WilliamDASILVA Should be better now on navigator

**Comment by WilliamDASILVA** [comment]
@Hartorn Work as expected on Edge :thumbsup: but still buggy on Firefox Quantum.

**Comment by Hartorn** [comment]
@WilliamDASILVA Could you give me an example of what's buggy ?
For me, it seems to work pretty well (Firefox Quantum 57.0.1, 64bits)
Also, do you have problem when editing, or when seeing the result ?
(If editing, this is much more minor)

**Comment by WilliamDASILVA** [comment]
Indeed, not a major issue

**Comment by Hartorn** [comment]
@WilliamDASILVA Ok, I will try to find the problem then. 
I label this as minor, since it's only in creation, not when editing or consulting.

**Comment by Azaret** [comment]
Is this have been fixed?
Because I've no issue with both Quantum 58 & 59.

**Comment by Hartorn** [comment]
@Azaret Yeah, still reproduced it.
The bug is only when creating an event, when typing the first characters.
